# action that installs nix, installs the flake, and then runs the pytest tests
name: CI

on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
            name: smsegal
            authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
            extraPullNames: nix-community
      - run: nix build
      - run: >
            nix develop --impure --command -- \
            pre-commit run --all-files
      - run: nix develop --impure --command pytest
